// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewdbhcxqccarcrxiiqwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3ZGJoY3hxY2NhcmNyeGlpcXd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1ODg4NTIsImV4cCI6MjA2NjE2NDg1Mn0.1qT3izgHXS79JvrMXZn85tzYE0XIn6IC78egeoQo7OA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);